// <auto-generated />
using BudgetPlanner.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlanner.API.Migrations
{
    [DbContext(typeof(IncomeContext))]
    [Migration("20240924074239_update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlanner.API.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wash",
                            IsDone = true,
                            Title = "Do the dishes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gently",
                            IsDone = false,
                            Title = "Pet the dog"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cosy",
                            IsDone = false,
                            Title = "Sleep in ur bed"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Swag",
                            IsDone = true,
                            Title = "Drip"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
